config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :job_entries
  resources :jobs
  devise_for :users

  post 'webhook', to: 'webhook#handle'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :job_entries
  belongs_to :user
end

app/models/job_entry.rb
class JobEntry < ApplicationRecord
  belongs_to :job
  has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :job_entry
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :job_entries, through: :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_entries_controller.rb
class JobEntriesController < ApplicationController
  before_action :set_job_entry, only: [:show, :edit, :update, :destroy]

  # GET /job_entries
  # GET /job_entries.json
  def index
    @job_entries = JobEntry.all
  end

  # GET /job_entries/1
  # GET /job_entries/1.json
  def show
  end

  # GET /job_entries/new
  def new
    @job_entry = JobEntry.new
  end

  # GET /job_entries/1/edit
  def edit
  end

  # POST /job_entries
  # POST /job_entries.json
  def create
    @job_entry = JobEntry.new(job_entry_params)

    respond_to do |format|
      if @job_entry.save
        format.html { redirect_to @job_entry, notice: 'Job entry was successfully created.' }
        format.json { render :show, status: :created, location: @job_entry }
      else
        format.html { render :new }
        format.json { render json: @job_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_entries/1
  # PATCH/PUT /job_entries/1.json
  def update
    respond_to do |format|
      if @job_entry.update(job_entry_params)
        format.html { redirect_to @job_entry, notice: 'Job entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_entry }
      else
        format.html { render :edit }
        format.json { render json: @job_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_entries/1
  # DELETE /job_entries/1.json
  def destroy
    @job_entry.destroy
    respond_to do |format|
      format.html { redirect_to job_entries_url, notice: 'Job entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_entry
      @job_entry = JobEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_entry_params
      params.require(:job_entry).permit(:job_id, :from, :until)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :user_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text, :job_entry_id)
    end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
    protect_from_forgery :except => :handle

    def handle
        begin
            event = JSON.parse(request.body.read)
            puts event
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_entries_helper.rb
module JobEntriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/views/job_entries/_form.html.erb
<%= form_with(model: job_entry, local: true) do |form| %>
  <% if job_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_entry.errors.count, "error") %> prohibited this job_entry from being saved:</h2>

      <ul>
        <% job_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.datetime_select :from %>
  </div>

  <div class="field">
    <%= form.label :until %>
    <%= form.datetime_select :until %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_entries/edit.html.erb
<h1>Editing Job Entry</h1>

<%= render 'form', job_entry: @job_entry %>

<%= link_to 'Show', @job_entry %> |
<%= link_to 'Back', job_entries_path %>

app/views/job_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Entries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Job</th>
      <th>From</th>
      <th>Until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_entries.each do |job_entry| %>
      <tr>
        <td><%= job_entry.user_id %></td>
        <td><%= job_entry.job_id %></td>
        <td><%= job_entry.from %></td>
        <td><%= job_entry.until %></td>
        <td><%= link_to 'Show', job_entry %></td>
        <td><%= link_to 'Edit', edit_job_entry_path(job_entry) %></td>
        <td><%= link_to 'Destroy', job_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Entry', new_job_entry_path %>

app/views/job_entries/new.html.erb
<h1>New Job Entry</h1>

<%= render 'form', job_entry: @job_entry %>

<%= link_to 'Back', job_entries_path %>

app/views/job_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @job_entry.user_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @job_entry.job_id %>
</p>

<p>
  <strong>From:</strong>
  <%= @job_entry.from %>
</p>

<p>
  <strong>Until:</strong>
  <%= @job_entry.until %>
</p>

<%= link_to 'Edit', edit_job_entry_path(@job_entry) %> |
<%= link_to 'Back', job_entries_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.user_id %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @job.user_id %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackTimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :job_entry_id %>
    <%= form.text_field :job_entry_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Job entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.text %></td>
        <td><%= note.job_entry_id %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>Job entry:</strong>
  <%= @note.job_entry_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>